### PR TITLE
Backend calls working on fetching the data. Nothing working yet with …

### PR DESCRIPTION
**Pull request by MikhailSorokin**
…the front end regarding the stuff even though I thought I had set it up properly. Needs to be looked at.

### CODE REVIEW

**Comment by MikhailSorokin** [comment]
Updated with a push.

**Comment by MikhailSorokin** [comment]
test

**Comment by MikhailSorokin** [comment]
Updated - look at messages from last commits.

**Review by b5er — COMMENTED** [review]
Which part do you need help with, or is this done on your end?

**Comment by MikhailSorokin** [comment]
When you test it:

- Images need to be displayed in a grid, not a vertical list.
- Blurbs over the images need to be fully covered.

**Pull request closed without merging**
